### ISSUE TITLE
AssertionError [ERR_ASSERTION]: Invalid public key

### ISSUE THREAD

**Issue by lingyiliu016** [tylerdiaz/ping-eos#4]
when I run "node pingPong.js" ,error occured!
Details are as follows:
{ AssertionError [ERR_ASSERTION]: Invalid public key
    at Object.PublicKey (/Users/changlingyi/node_modules/eosjs/node_modules/eosjs-ecc/lib/key_public.js:24:9)
    at /Users/changlingyi/node_modules/eosjs/lib/index.js:191:30
    at Array.map (<anonymous>)
    at Object.signProvider (/Users/changlingyi/node_modules/eosjs/lib/index.js:185:17)
    at /Users/changlingyi/node_modules/eosjs/lib/write-api.js:625:23
    at /Users/changlingyi/node_modules/eosjs/lib/write-api.js:771:7
    at /Users/changlingyi/node_modules/eosjs/node_modules/eosjs-api/lib/exported-helpers.js:69:7
    at /Users/changlingyi/node_modules/eosjs/node_modules/eosjs-api/lib/exported-helpers.js:79:7
    at callback (/Users/changlingyi/node_modules/eosjs/node_modules/eosjs-api/lib/process-args.js:70:9)
    at callback (/Users/changlingyi/node_modules/eosjs/node_modules/eosjs-api/lib/apigen.js:99:9)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
The following is the content of my pingPong.js file.

let EOS = require('eosjs')

eos = EOS.Localnet({
	keyProvider:['PW5Jj6BExXZ5cYd6VpKktgEugoF9CGWEjbmgh9am27XsFMuorLffi'],
	httpEndpoint:'http://127.0.0.1:8888'
})

eos.contract('child.acnt').then((contract) => {
	contract.ping("child.acnt",{authorization:['child.acnt']}).then((res) => {
		console.log(res)
	})
})
ping smart contract is set to EOS blockchanin, and when I use command line to interact to ping smart contract is ok! 
when I run  "node pingPong.js" , EOS nodeos didn't receive any message
What's the wrong? what should I do?

**Comment by lingyiliu016** [comment]
when I run "node pingPong.js" ,error occured!
Details are as follows:
{ AssertionError [ERR_ASSERTION]: Invalid public key
at Object.PublicKey (/Users/changlingyi/node_modules/eosjs/node_modules/eosjs-ecc/lib/key_public.js:24:9)
at /Users/changlingyi/node_modules/eosjs/lib/index.js:191:30
at Array.map ()
at Object.signProvider (/Users/changlingyi/node_modules/eosjs/lib/index.js:185:17)
at /Users/changlingyi/node_modules/eosjs/lib/write-api.js:625:23
at /Users/changlingyi/node_modules/eosjs/lib/write-api.js:771:7
at /Users/changlingyi/node_modules/eosjs/node_modules/eosjs-api/lib/exported-helpers.js:69:7
at /Users/changlingyi/node_modules/eosjs/node_modules/eosjs-api/lib/exported-helpers.js:79:7
at callback (/Users/changlingyi/node_modules/eosjs/node_modules/eosjs-api/lib/process-args.js:70:9)
at callback (/Users/changlingyi/node_modules/eosjs/node_modules/eosjs-api/lib/apigen.js:99:9)
generatedMessage: false,
name: 'AssertionError [ERR_ASSERTION]',
code: 'ERR_ASSERTION',
actual: false,
expected: true,
operator: '==' }
The following is the content of my pingPong.js file.
`
let EOS = require('eosjs')

eos = EOS.Localnet({
keyProvider:['PW5Jj6BExXZ5cYd6VpKktgEugoF9CGWEjbmgh9am27XsFMuorLffi'],
httpEndpoint:'http://127.0.0.1:8888'
})

eos.contract('child.acnt').then((contract) => {
contract.ping("child.acnt",{authorization:['child.acnt']}).then((res) => {
console.log(res)
})
})
`
ping smart contract is set to EOS blockchanin, and when I use command line to interact to ping smart contract is ok!
when I run "node pingPong.js" , EOS nodeos didn't receive any message
What's the wrong? what should I do?

**Comment by mesqueeb** [comment]
@lingyiliu016 what was the solution?
